[workspace]
members = [
    "leaf",
    "leaf-bin",
    "leaf-ffi",
]
default-members = ["leaf-bin"]

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"

[patch.crates-io]
mio = { git = "https://github.com/YtFlow/mio-noafd" }
